Dedicated `BoundSymbol` for `autograd_function_apply`
Though it seems that the modification of
`jit_ctx.computation_trace.bound_symbols` leads to an weird error of
missing return statement of computation trace:
```
Traceback (most recent call last):
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/example_bwd_body.py", line 202, in <module>
    main()
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/example_bwd_body.py", line 193, in main
    out, = jitted(l_stack0, l_labels0)
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mkozuki/ghq/github.com/crcrpar/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/core/module.py", line 80, in forward
    res = self._forward_fn(*args, **kwargs)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/__init__.py", line 745, in fn_
    cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/core/langctxs.py", line 136, in _fn
    result = fn(*args, **kwargs)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/__init__.py", line 230, in cache_info_wrapper
    res = fn(*args, **kwargs)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/__init__.py", line 648, in get_computation_and_inputs
    computation_trc = dce(computation_trc)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/core/transform_common.py", line 101, in dce
    flat_trace_outputs, _ = tree_flatten(trace.output)
  File "/home/mkozuki/ghq/github.com/Lightning-AI/lightning-thunder/thunder/core/trace.py", line 202, in output
    assert False, "Trace has no return, and so no output"
AssertionError: Trace has no return, and so no output
```

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>